include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    library_private_types_in_public_api: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
